---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-updater-secret
  namespace: duckdns-updater
spec:
  encryptedData:
    TOKEN: <encrypted token>
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: duckdns-updater-secret
      namespace: duckdns-updater
    type: Opaque
