http:
  routers:
    https:
      rule: "ClientIP(`0.0.0.0/0`)"
      entryPoints: [ "websecure" ]
      service: backend-https
    http:
      rule: "ClientIP(`0.0.0.0/0`)"
      entryPoints: [ "web" ]
      service: backend-http

  services:
    backend-http:
      loadBalancer:
        servers:
        - url: "http://whoami"
    backend-https:
      loadBalancer:
        servers:
        - url: "http://whoami"
