kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-pv-claim
  namespace: pihole
  labels:
    app: pihole
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
