services:
  haproxy:
    image: haproxy:3.1.1-alpine3.21
    container_name: haproxy
    user: "root"
    restart: always
    network_mode: "host"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
