---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: prometheus
spec:
  encryptedData:
    username: sealedSecretsEncryptedData
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: basic-auth
      namespace: prometheus
    type: Opaque
