kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myst-pv-claim
  namespace: myst
  labels:
    app: myst
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
