---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-secret
  namespace: loki
spec:
  encryptedData:
    MAXMIND_ACCOUNT_ID: sealedSecretsEncryptedData
    MAXMIND_LICENSE_KEY: sealedSecretsEncryptedData
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: loki-secret
      namespace: loki
    type: Opaque
