apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-rules-pv
  namespace: loki
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /home/bunetz/data/loki/rules
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bunetzk8s-agent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-rules-pvc
  namespace: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: loki-rules-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-chunks-pv
  namespace: loki
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /home/bunetz/data/loki/chunks
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bunetzk8s-agent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-chunks-pvc
  namespace: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: loki-chunks-pv
  storageClassName: local-path