---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: grafana
spec:
  encryptedData:
    ADMIN_PASSWORD: sealedSecretsEncryptedData
    ADMIN_USER: sealedSecretsEncryptedData
    database_password: sealedSecretsEncryptedData
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: grafana-secret
      namespace: grafana
    type: Opaque
