---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: sealedSecretsEncryptedData 
    DATABASE_URL: sealedSecretsEncryptedData
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: vaultwarden-secret
      namespace: vaultwarden
    type: Opaque
