apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.2-alpine3.19
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: db-port
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: ./data
              name: postgredb
          resources:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 512Mi
              cpu: 300m
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
