---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBF3pqz8bzlXQGfobQroDPNN+FefPwUkeH3WfRBbujwGpunk19kFcgdZ8gABCoTnbXMJo2qUcCXJm4U/q/cmf5N6L14LS4TisnK3tfzRWY+EAdk3PawB7dO/6x1bN1hFN4cLBF01yGnhPE12CcFHDlVjr7SDj7ZjSfcpP42d5kQcrGwbFZq3QBmzVtfiavkZVRuO7DWISrG7HCkxSdOyz1Vjv73Cq7Xnnt1SYLsOC0mNpb966qK80EbxqD0pHqrpHaGx4LWLBWaLzZrQyY6RKlId1ihLrXconh/pouYUfzkIWakM3qh+xtLnNSLqzrW6Gp22LIWpwHk9ZCeSu4fW7E3IVIwIHEpJSzF7SRfeiWox8yhDlbEJh+OA3NiebKVmovUvUFHMmkFSfJtqCTQ5ZXMSqo8+d8MeLvd2XTCINeFmCtchk0DCx/TeM9o8LXDQJIgHAFjM2yxBTfXFv3lgmEtx6kVBbuJ5bYYQUAa/LYq3sV/12i32FY8hyIIaNsmNuhhnmwNCZEDmvPvfVzD7MTfZjjz/HeTRJbIpTET21p+kGK4at4nw4AphxESDUrsvgrmR2Fc7HhmHxiVqbCROy1AJO/hCBYB8osfQNDkWtJnYlzjl7o9khqtMn5cm/cLAZiU/E83WqMLV2/oBvdPaALl8L/9wZ3bAhr9noz9Kgx0PgfYx7BI7p3U6JdQa++v+pU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: postgres-secret
      namespace: postgres
    type: Opaque
