apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres
spec:
  ports:
    - name: db-port
      port: 5432
      targetPort: db-port
      protocol: TCP
  selector:
    app: postgres
