tcp:
  routers:
    https:
      rule: "HostSNI(`*`)"
      entryPoints: [ "websecure" ]
      service: backend-https
      tls:
        passthrough: true
    http:
      rule: "HostSNI(`*`)"
      entryPoints: [ "web" ]
      service: backend-http
    k8s:
      rule: "HostSNI(`*`)"
      entryPoints: [ "k8s" ]
      service: k8s
  services:
    backend-http:
      loadBalancer:
        proxyProtocol:
          version: 2
        servers:
        - address: "traefik2:80"
    backend-https:
      loadBalancer:
        proxyProtocol:
          version: 2
        servers:
        - address: "traefik2:443"
    k8s:
      loadBalancer:
        servers:
        - address: "traefik2:6443"
