version: "3"
services:
  traefik:
    image: traefik:v2.11
    container_name: traefik-proxy
    restart: always
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - ./traefik.yaml:/traefik.yaml
      - ./config.yaml:/config.yaml

  traefik2:
    image: traefik:v2.11
    container_name: traefik-proxy2
    restart: always
    ports:
      - 8081:8080
      - 81:80
    volumes:
      - ./dev/traefik.yaml:/traefik.yaml
      - ./dev/config.yaml:/config.yaml

  whoami:
    image: "traefik/whoami"
    container_name: whoami
