kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homebridge-pv-claim
  namespace: homebridge
  labels:
    app: homebridge
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
