---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ip-secret
  namespace: ip
spec:
  encryptedData:
    PASSWORD: sealedSecretsEncryptedData
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: ip-secret
      namespace: ip
    type: Opaque
