configs:
  params:
    server.insecure: true

controller:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"

dex:
  enabled: false

server:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"

repoServer:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8084"

applicationSet:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

notifications:
  enabled: false
