apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  DB_HOSTNAME: postgres.immich.svc
  DB_PORT: "5432"
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  REDIS_HOSTNAME: redis.immich.svc
  REDIS_PORT: "6379"
