apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data-pv
  namespace: immich
spec:
  capacity:
    storage: 128G
  accessModes:
  - ReadWriteMany
  storageClassName: local-path
  local:
    path: /home/bunetz/data/immich-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bunetzk8s
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-data-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128G
  volumeName: immich-data-pv
  storageClassName: local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-postgres-pvc
  namespace: immich
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-machinelearning-pv
  namespace: immich
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  storageClassName: local-path
  local:
    path: /home/bunetz/data/immich-machinelearning
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bunetzk8s
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-machinelearning-pvc
  namespace: immich
spec:
  volumeName: immich-machinelearning-pv
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
