---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azblob-secret
  namespace: longhorn
spec:
  encryptedData:
    AZBLOB_ACCOUNT_KEY: sealedSecretsEncryptedData
    AZBLOB_ACCOUNT_NAME: sealedSecretsEncryptedData
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: azblob-secret
      namespace: longhorn
    type: Opaque
